version: '3.8'

services:

  elasticsearch_service:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana_service:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch_service:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch_service:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch_service

  apm_service:
    container_name: apm_container
    image: docker.elastic.co/apm/apm-server:7.8.0
    ports:
      - "8200:8200"
    links:
      - elasticsearch_service
      - kibana_service
    depends_on:
      - elasticsearch_service
      - kibana_service
